uuid = "215c759a-4c58-4147-99e8-dfb3921ef1a0"
authors = ["Kristof Cools <krcools@gmail.com>"]
version = "0.1.0"

[deps]
CompScienceMeshes = "3e66a162-7b8c-5da0-b8f8-124ecd2c3ae1"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
CompScienceMeshes = "^0.2.7"
Makie = "^0.11.1"
